/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cstute;

import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Achala Piyarathna
 */
public class viewCustomerList extends javax.swing.JFrame {

    /**
     * Creates new form viewCustomerList
     */
    static boolean flag;
    DefaultTableModel model;
    static List<String> customerDetails;
    
    public viewCustomerList() {
        initComponents();
        setTitle("eBank");
        ImageIcon img = new ImageIcon("src/icon.png");
        this.setLocationRelativeTo(null);
        
        model = (DefaultTableModel) jTable3.getModel();
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int index = jTable3.getSelectedRow();
                dispose();
                SearchEmpView.start(customerDetails.get(index));
//                dispose();
            }
        });
        insertToTable();
    }

    public void insertToTable() {
        customerDetails = retrieveCustomerList();
        for (String emp : customerDetails) {
            System.out.println(emp);
            model.insertRow(model.getRowCount(), new Object[]{emp.split("&")[0], emp.split("&")[5], emp.split("&")[7]});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        manageEmployee1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        manageEmployee2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Postion", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        manageEmployee2.setText("Log Out");
        manageEmployee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployee2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageEmployee2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageEmployee1)
                    .addComponent(manageEmployee2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void manageEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployee1ActionPerformed
        // TODO add your handling code here:
        Selections.startSelection(flag);
        dispose();
    }//GEN-LAST:event_manageEmployee1ActionPerformed

    private void manageEmployee2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployee2ActionPerformed
        // TODO add your handling code here:
        Login.start();
        dispose();
    }//GEN-LAST:event_manageEmployee2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void viewCstList() {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCustomerList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton manageEmployee1;
    private javax.swing.JButton manageEmployee2;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> retrieveCustomerList() {
        ebank.RetrieveData_Service service = new ebank.RetrieveData_Service();
        ebank.RetrieveData port = service.getRetrieveDataPort();
        return port.retrieveCustomerList();
    }

}
